name: usat_calendar
description: Une application pour l'organisation des matchs et entraînements du club USAT

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  logger: ^1.3.0
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2

  # STATE MANAGEMENT
  auto_route: ^6.0.0+1
  firebase_core: ^2.24.0
  firebase_database: ^10.2.5
  firebase_auth: ^4.15.0

  # FIREBASE
  # GITHUB

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
